# permissions to do viewer virtualmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachine-viewer-role
rules:
- apiGroups:
  - infra.loch.com
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.loch.com
  resources:
  - virtualmachines/status
  verbs:
  - get
